// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeMirror: typeof import('./components/CodeMirror.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    Playground: typeof import('./components/Playground.vue')['default']
    Snap: typeof import('./components/Snap.vue')['default']
    Snapshots: typeof import('./components/Snapshots.vue')['default']
  }
}
