/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeMirror: typeof import('./components/CodeMirror.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    Playground: typeof import('./components/Playground.vue')['default']
    Snap: typeof import('./components/Snap.vue')['default']
    Snapshots: typeof import('./components/Snapshots.vue')['default']
  }
}
